//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PolarionMcp.Client.ConnectedServices.SessionWebService
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://ws.polarion.com/SessionWebService", ConfigurationName="PolarionMcp.Client.ConnectedServices.SessionWebService.SessionWebService")]
    public interface SessionWebService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<PolarionMcp.Client.ConnectedServices.SessionWebService.beginTransactionResponse> beginTransactionAsync(PolarionMcp.Client.ConnectedServices.SessionWebService.beginTransactionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<PolarionMcp.Client.ConnectedServices.SessionWebService.endSessionResponse> endSessionAsync(PolarionMcp.Client.ConnectedServices.SessionWebService.endSessionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<PolarionMcp.Client.ConnectedServices.SessionWebService.endTransactionResponse> endTransactionAsync(PolarionMcp.Client.ConnectedServices.SessionWebService.endTransactionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<PolarionMcp.Client.ConnectedServices.SessionWebService.hasSubjectResponse> hasSubjectAsync(PolarionMcp.Client.ConnectedServices.SessionWebService.hasSubjectRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<PolarionMcp.Client.ConnectedServices.SessionWebService.logInResponse> logInAsync(PolarionMcp.Client.ConnectedServices.SessionWebService.logInRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<PolarionMcp.Client.ConnectedServices.SessionWebService.logInWithTokenResponse> logInWithTokenAsync(PolarionMcp.Client.ConnectedServices.SessionWebService.logInWithTokenRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<PolarionMcp.Client.ConnectedServices.SessionWebService.transactionExistsResponse> transactionExistsAsync(PolarionMcp.Client.ConnectedServices.SessionWebService.transactionExistsRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="beginTransaction", WrapperNamespace="http://ws.polarion.com/SessionWebService-impl", IsWrapped=true)]
    public partial class beginTransactionRequest
    {
        
        public beginTransactionRequest()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="beginTransactionResponse", WrapperNamespace="http://ws.polarion.com/SessionWebService-impl", IsWrapped=true)]
    public partial class beginTransactionResponse
    {
        
        public beginTransactionResponse()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="endSession", WrapperNamespace="http://ws.polarion.com/SessionWebService-impl", IsWrapped=true)]
    public partial class endSessionRequest
    {
        
        public endSessionRequest()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="endSessionResponse", WrapperNamespace="http://ws.polarion.com/SessionWebService-impl", IsWrapped=true)]
    public partial class endSessionResponse
    {
        
        public endSessionResponse()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="endTransaction", WrapperNamespace="http://ws.polarion.com/SessionWebService-impl", IsWrapped=true)]
    public partial class endTransactionRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.polarion.com/SessionWebService-impl", Order=0)]
        public bool rollback;
        
        public endTransactionRequest()
        {
        }
        
        public endTransactionRequest(bool rollback)
        {
            this.rollback = rollback;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="endTransactionResponse", WrapperNamespace="http://ws.polarion.com/SessionWebService-impl", IsWrapped=true)]
    public partial class endTransactionResponse
    {
        
        public endTransactionResponse()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="hasSubject", WrapperNamespace="http://ws.polarion.com/SessionWebService-impl", IsWrapped=true)]
    public partial class hasSubjectRequest
    {
        
        public hasSubjectRequest()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="hasSubjectResponse", WrapperNamespace="http://ws.polarion.com/SessionWebService-impl", IsWrapped=true)]
    public partial class hasSubjectResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.polarion.com/SessionWebService-impl", Order=0)]
        public bool hasSubjectReturn;
        
        public hasSubjectResponse()
        {
        }
        
        public hasSubjectResponse(bool hasSubjectReturn)
        {
            this.hasSubjectReturn = hasSubjectReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="logIn", WrapperNamespace="http://ws.polarion.com/SessionWebService-impl", IsWrapped=true)]
    public partial class logInRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.polarion.com/SessionWebService-impl", Order=0)]
        public string userName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.polarion.com/SessionWebService-impl", Order=1)]
        public string password;
        
        public logInRequest()
        {
        }
        
        public logInRequest(string userName, string password)
        {
            this.userName = userName;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="logInResponse", WrapperNamespace="http://ws.polarion.com/SessionWebService-impl", IsWrapped=true)]
    public partial class logInResponse
    {
        
        public logInResponse()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="logInWithToken", WrapperNamespace="http://ws.polarion.com/SessionWebService-impl", IsWrapped=true)]
    public partial class logInWithTokenRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.polarion.com/SessionWebService-impl", Order=0)]
        public string mechanism;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.polarion.com/SessionWebService-impl", Order=1)]
        public string username;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.polarion.com/SessionWebService-impl", Order=2)]
        public string token;
        
        public logInWithTokenRequest()
        {
        }
        
        public logInWithTokenRequest(string mechanism, string username, string token)
        {
            this.mechanism = mechanism;
            this.username = username;
            this.token = token;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="logInWithTokenResponse", WrapperNamespace="http://ws.polarion.com/SessionWebService-impl", IsWrapped=true)]
    public partial class logInWithTokenResponse
    {
        
        public logInWithTokenResponse()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="transactionExists", WrapperNamespace="http://ws.polarion.com/SessionWebService-impl", IsWrapped=true)]
    public partial class transactionExistsRequest
    {
        
        public transactionExistsRequest()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="transactionExistsResponse", WrapperNamespace="http://ws.polarion.com/SessionWebService-impl", IsWrapped=true)]
    public partial class transactionExistsResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.polarion.com/SessionWebService-impl", Order=0)]
        public bool transactionExistsReturn;
        
        public transactionExistsResponse()
        {
        }
        
        public transactionExistsResponse(bool transactionExistsReturn)
        {
            this.transactionExistsReturn = transactionExistsReturn;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public interface SessionWebServiceChannel : PolarionMcp.Client.ConnectedServices.SessionWebService.SessionWebService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public partial class SessionWebServiceClient : System.ServiceModel.ClientBase<PolarionMcp.Client.ConnectedServices.SessionWebService.SessionWebService>, PolarionMcp.Client.ConnectedServices.SessionWebService.SessionWebService
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public SessionWebServiceClient() : 
                base(SessionWebServiceClient.GetDefaultBinding(), SessionWebServiceClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.SessionWebService.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SessionWebServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(SessionWebServiceClient.GetBindingForEndpoint(endpointConfiguration), SessionWebServiceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SessionWebServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(SessionWebServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SessionWebServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(SessionWebServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SessionWebServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PolarionMcp.Client.ConnectedServices.SessionWebService.beginTransactionResponse> PolarionMcp.Client.ConnectedServices.SessionWebService.SessionWebService.beginTransactionAsync(PolarionMcp.Client.ConnectedServices.SessionWebService.beginTransactionRequest request)
        {
            return base.Channel.beginTransactionAsync(request);
        }
        
        public System.Threading.Tasks.Task<PolarionMcp.Client.ConnectedServices.SessionWebService.beginTransactionResponse> beginTransactionAsync()
        {
            PolarionMcp.Client.ConnectedServices.SessionWebService.beginTransactionRequest inValue = new PolarionMcp.Client.ConnectedServices.SessionWebService.beginTransactionRequest();
            return ((PolarionMcp.Client.ConnectedServices.SessionWebService.SessionWebService)(this)).beginTransactionAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PolarionMcp.Client.ConnectedServices.SessionWebService.endSessionResponse> PolarionMcp.Client.ConnectedServices.SessionWebService.SessionWebService.endSessionAsync(PolarionMcp.Client.ConnectedServices.SessionWebService.endSessionRequest request)
        {
            return base.Channel.endSessionAsync(request);
        }
        
        public System.Threading.Tasks.Task<PolarionMcp.Client.ConnectedServices.SessionWebService.endSessionResponse> endSessionAsync()
        {
            PolarionMcp.Client.ConnectedServices.SessionWebService.endSessionRequest inValue = new PolarionMcp.Client.ConnectedServices.SessionWebService.endSessionRequest();
            return ((PolarionMcp.Client.ConnectedServices.SessionWebService.SessionWebService)(this)).endSessionAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PolarionMcp.Client.ConnectedServices.SessionWebService.endTransactionResponse> PolarionMcp.Client.ConnectedServices.SessionWebService.SessionWebService.endTransactionAsync(PolarionMcp.Client.ConnectedServices.SessionWebService.endTransactionRequest request)
        {
            return base.Channel.endTransactionAsync(request);
        }
        
        public System.Threading.Tasks.Task<PolarionMcp.Client.ConnectedServices.SessionWebService.endTransactionResponse> endTransactionAsync(bool rollback)
        {
            PolarionMcp.Client.ConnectedServices.SessionWebService.endTransactionRequest inValue = new PolarionMcp.Client.ConnectedServices.SessionWebService.endTransactionRequest();
            inValue.rollback = rollback;
            return ((PolarionMcp.Client.ConnectedServices.SessionWebService.SessionWebService)(this)).endTransactionAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PolarionMcp.Client.ConnectedServices.SessionWebService.hasSubjectResponse> PolarionMcp.Client.ConnectedServices.SessionWebService.SessionWebService.hasSubjectAsync(PolarionMcp.Client.ConnectedServices.SessionWebService.hasSubjectRequest request)
        {
            return base.Channel.hasSubjectAsync(request);
        }
        
        public System.Threading.Tasks.Task<PolarionMcp.Client.ConnectedServices.SessionWebService.hasSubjectResponse> hasSubjectAsync()
        {
            PolarionMcp.Client.ConnectedServices.SessionWebService.hasSubjectRequest inValue = new PolarionMcp.Client.ConnectedServices.SessionWebService.hasSubjectRequest();
            return ((PolarionMcp.Client.ConnectedServices.SessionWebService.SessionWebService)(this)).hasSubjectAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PolarionMcp.Client.ConnectedServices.SessionWebService.logInResponse> PolarionMcp.Client.ConnectedServices.SessionWebService.SessionWebService.logInAsync(PolarionMcp.Client.ConnectedServices.SessionWebService.logInRequest request)
        {
            return base.Channel.logInAsync(request);
        }
        
        public System.Threading.Tasks.Task<PolarionMcp.Client.ConnectedServices.SessionWebService.logInResponse> logInAsync(string userName, string password)
        {
            PolarionMcp.Client.ConnectedServices.SessionWebService.logInRequest inValue = new PolarionMcp.Client.ConnectedServices.SessionWebService.logInRequest();
            inValue.userName = userName;
            inValue.password = password;
            return ((PolarionMcp.Client.ConnectedServices.SessionWebService.SessionWebService)(this)).logInAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PolarionMcp.Client.ConnectedServices.SessionWebService.logInWithTokenResponse> PolarionMcp.Client.ConnectedServices.SessionWebService.SessionWebService.logInWithTokenAsync(PolarionMcp.Client.ConnectedServices.SessionWebService.logInWithTokenRequest request)
        {
            return base.Channel.logInWithTokenAsync(request);
        }
        
        public System.Threading.Tasks.Task<PolarionMcp.Client.ConnectedServices.SessionWebService.logInWithTokenResponse> logInWithTokenAsync(string mechanism, string username, string token)
        {
            PolarionMcp.Client.ConnectedServices.SessionWebService.logInWithTokenRequest inValue = new PolarionMcp.Client.ConnectedServices.SessionWebService.logInWithTokenRequest();
            inValue.mechanism = mechanism;
            inValue.username = username;
            inValue.token = token;
            return ((PolarionMcp.Client.ConnectedServices.SessionWebService.SessionWebService)(this)).logInWithTokenAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PolarionMcp.Client.ConnectedServices.SessionWebService.transactionExistsResponse> PolarionMcp.Client.ConnectedServices.SessionWebService.SessionWebService.transactionExistsAsync(PolarionMcp.Client.ConnectedServices.SessionWebService.transactionExistsRequest request)
        {
            return base.Channel.transactionExistsAsync(request);
        }
        
        public System.Threading.Tasks.Task<PolarionMcp.Client.ConnectedServices.SessionWebService.transactionExistsResponse> transactionExistsAsync()
        {
            PolarionMcp.Client.ConnectedServices.SessionWebService.transactionExistsRequest inValue = new PolarionMcp.Client.ConnectedServices.SessionWebService.transactionExistsRequest();
            return ((PolarionMcp.Client.ConnectedServices.SessionWebService.SessionWebService)(this)).transactionExistsAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        #if !NET6_0_OR_GREATER
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        #endif
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.SessionWebService))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.SessionWebService))
            {
                return new System.ServiceModel.EndpointAddress("https://testdrive.polarion.com/polarion/ws/services/SessionWebService");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return SessionWebServiceClient.GetBindingForEndpoint(EndpointConfiguration.SessionWebService);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return SessionWebServiceClient.GetEndpointAddress(EndpointConfiguration.SessionWebService);
        }
        
        public enum EndpointConfiguration
        {
            
            SessionWebService,
        }
    }
}
